name = "ayush-portfolio"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[vars]
# Add any environment variables here if needed in the future
