export const projects = [
  {
    slug: "careerlens",
    order: "01",
    status: "Live",
    title: "CareerLens",
    description:
      "A resume intelligence platform that evaluates candidate fit against job descriptions and skill expectations.",
    cardIcons: ["nextjs", "python", "fastapi", "postgresql"],
    cover: {
      type: "image",
      image: "/projects/CareerLensUI.png",
      heading: "CareerLens",
    },
    liveUrl: "https://careerlens-eosin.vercel.app/",
    sourceUrl: "https://github.com/AyushPawshe08/CareerLens2",
    about: [
      "CareerLens analyzes a resume against a target job description to produce a structured view of role alignment, ATS readiness, and missing competencies. The platform converts raw resume content into actionable career signals.",
      "It generates an ATS score, skill-gap analysis, role recommendations, improvement suggestions, and a concise resume summary. The system also provides technical, behavioral, and HR interview questions tailored to the candidate profile.",
      "The backend uses FastAPI with Celery and Redis for asynchronous analysis workflows, while PostgreSQL on Neon stores application data. The experience is delivered through a Next.js and React interface with JWT-based authentication.",
    ],
    stack: [
      "react",
      "vite",
      "tailwind",
      "python",
      "fastapi",
      "postgresql",
      "neon",
      "docker",
      "jwt",
    ],
  },
  {
    slug: "techdocsmcp",
    order: "02",
    status: "Local",
    title: "DocScout - MCP Server",
    description:
      "An MCP server that lets an LLM look up current official documentation for any library and answer with links to its sources.",
    cardIcons: ["python", "fastmcp", "mcp"],
    cover: {
      type: "image",
      image: "/projects/DocScoutUI.png",
      heading: "DocScout MCP",
      subheading: "Documentation retrieval for LLMs",
    },
    liveUrl: "https://github.com/AyushPawshe08/TechDocs-MCP-Server",
    sourceUrl: "https://github.com/AyushPawshe08/TechDocs-MCP-Server",
    about: [
      "LLMs often answer coding questions from memory, and that memory goes stale. DocScout is an MCP server that gives the model a get_docs tool, so it can read a library's current official documentation instead.",
      "Given a library name and a topic, it finds the library's official docs site, searches only that site with Tavily, fetches the top pages, and returns the cleaned text with each page's title and URL so answers can cite their sources.",
      "Any library works. 90+ popular ones, such as React, FastAPI, NumPy and LangChain, are preconfigured. For the rest, it finds the docs site by searching and remembers the result. If that guess is wrong, the model can pass the docs site directly.",
      "Built with Python and FastMCP, using HTTPX to fetch pages and Trafilatura to extract readable text. It runs locally over stdio, so any MCP client, such as Claude Desktop, can use it.",
    ],
    stack: ["python", "fastmcp", "mcp", "trafilatura"],
  },
  {
    slug: "neuroRAG",
    order: "03",
    status: "Local",
    title: "NeuroRAG",
    description:
      "Multimodal RAG system for brain MRI analysis — BioMedCLIP + Qdrant retrieval with Gemini-generated, evidence-grounded diagnostic explanations.",
    cardIcons: ["pytorch", "qdrant", "rag", "gradio", "docker"],
    cover: {
      type: "image",
      image: "/projects/NeuroRAGUI.png",
      heading: "NeuroRAG",
      subheading: "Multimodal RAG system for brain MRI analysis.",
    },
    liveUrl: "https://github.com/AyushPawshe08/NeuroRAG",
    sourceUrl: "https://github.com/AyushPawshe08/NeuroRAG",
    about: [
      "NeuroRAG is a multimodal retrieval-augmented generation (RAG) platform engineered for brain MRI analysis, connecting complex biomedical scans directly with diagnostic context and clinical knowledge.",
      "The system uses BioMedCLIP (powered by PyTorch and Hugging Face transformers) to generate joint image-text embeddings from MRI scans, storing and indexing them in a Qdrant vector database for high-accuracy similarity search across confirmed medical cases.",
      "Retrieved case contexts and patient MRI representations are passed to Google Gemini to formulate structured, evidence-grounded diagnostic explanations, delivered through a Gradio interface containerized with Docker.",
    ],
    stack: [
      "python",
      "pytorch",
      "qdrant",
      "rag",
      "fastapi",
      "gradio",
      "docker",
      "huggingface",
    ],
  },
  {
    slug: "querymind",
    order: "04",
    status: "Local",
    title: "QueryMind",
    description:
      "Autonomous multi-agent research platform built with LangGraph, Google Gemini, and Tavily that searches, analyzes, critiques, and synthesizes web sources into cited technical reports.",
    cardIcons: ["python", "langgraph", "langchain", "tavily", "postgresql"],
    cover: {
      type: "image",
      image: "/projects/QueryMindUI.png",
      heading: "QueryMind",
      subheading: "Multi-agent research assistant for discovering, extracting, and summarizing technical material.",
    },
    liveUrl: "https://github.com/AyushPawshe08/QueryMind",
    sourceUrl: "https://github.com/AyushPawshe08/QueryMind",
    about: [
      "QueryMind is an autonomous multi-agent research platform that takes a research question, plans a set of searches, and dispatches multiple agents to gather and analyze the most relevant sources in parallel.",
      "Each agent extracts claims and evidence relevant to the question using LangGraph for multi-agent orchestration and Google Gemini for reasoning, while Tavily provides intelligent web search capabilities and Firecrawl extracts and parses web content.",
      "A synthesis step merges findings into a single source-backed summary with inline citations, which can be exported as PDF. The pipeline is built in Python with Streamlit for the interactive interface and PostgreSQL for persistent data storage.",
    ],
    stack: [
      "python",
      "langgraph",
      "langchain",
      "gemini",
      "streamlit",
      "tavily",
      "postgresql",
      "firecrawl",
      "beautifulsoup4",
    ],
  },
  {
    slug: "credit-risk-underwriting",
    order: "05",
    status: "Local",
    title: "Credit Risk Underwriting",
    description:
      "Explainable credit risk underwriting system using LightGBM, SHAP, FastAPI, and Flask to predict loan default risk and generate rejection reason candidates.",
    cardIcons: ["python", "lightgbm", "xgboost", "shap", "fastapi", "flask"],
    cover: {
      type: "image",
      image: "/projects/CreditCardUI.png",
      heading: "Credit Risk Underwriting",
      subheading: "End-to-end loan default prediction with explainability.",
    },
    liveUrl:
      "https://github.com/AyushPawshe08/Credit-Risk-Underwriting-ML-System",
    sourceUrl:
      "https://github.com/AyushPawshe08/Credit-Risk-Underwriting-ML-System",
    about: [
      "Built a complete credit risk pipeline on a 32K+ Kaggle dataset covering data cleaning, train-test splitting, feature engineering, and model benchmarking. Engineered financial features such as DTI proxy, interest burden, income-to-loan ratio, employment stability ratio, and credit history ratio.",
      "Benchmarked Logistic Regression, Random Forest, XGBoost, and LightGBM using imbalanced-classification metrics (PR-AUC, ROC-AUC, Precision, Recall, F1). Achieved best performance with LightGBM: PR-AUC 0.9039 and ROC-AUC 0.9485.",
      "Integrated SHAP explainability to generate model-based rejection reason candidates for high-risk applicants. Deployed via FastAPI backend with production-style endpoints (/health, /metadata, /predict) and an interactive Flask loan-underwriting dashboard with real-time decisions.",
    ],
    stack: [
      "python",
      "pandas",
      "numpy",
      "scikit-learn",
      "lightgbm",
      "xgboost",
      "shap",
      "fastapi",
      "uvicorn",
      "flask",
      "joblib",
      "html",
      "css",
    ],
  },
  {
    slug: "ai-learning-pipeline",
    order: "06",
    status: "Live",
    title: "AI Learning Pipeline",
    description:
      "Comprehensive AI-powered learning system that transforms topics into structured educational content — generates learning objectives, explanations, code examples, quizzes, and revision notes using Groq AI and LangGraph.",
    cardIcons: ["python", "langgraph", "langchain", "fastapi"],
    cover: {
      type: "image",
      image: "/projects/AILearnUI.png",
      heading: "AI Learning Pipeline",
      subheading: "Transform any topic into a complete learning module.",
    },
    liveUrl: "https://ai-prep-tawny.vercel.app/",
    sourceUrl: "https://github.com/AyushPawshe08/AI_Prep",
    about: [
      "AI Learning Pipeline is an intelligent educational platform that transforms any topic into comprehensive, structured learning materials. The system automates the entire learning workflow using cutting-edge AI technologies.",
      "The pipeline leverages Groq's fast LLM inference and LangGraph for workflow orchestration to generate: learning objectives, detailed explanations with real-world analogies, technical deep-dives, practical code examples, interactive quizzes, answer keys, and revision notes.",
      "Built with FastAPI for high-performance API handling, Streamlit for an intuitive user interface, and ReportLab for PDF generation. Users can export complete learning modules as professionally formatted PDF documents for offline study.",
    ],
    stack: [
      "python",
      "fastapi",
      "groq",
      "langchain",
      "langgraph",
      "streamlit",
      "reportlab",
      "pydantic",
    ],
  },
  {
    slug: "hotshot",
    order: "07",
    status: "Live",
    title: "HotShot",
    description:
      "Fast URL shortener with QR code generation, custom aliases, expiry control, click tracking, and a local dashboard for managing links.",
    cardIcons: ["react", "vite", "tailwind", "fastapi", "docker", "qrcode"],
    cover: {
      type: "image",
      image: "/projects/HotShotUI.png",
      heading: "HotShot",
      subheading: "Turn long links into short, shareable URLs with QR codes.",
    },
    liveUrl: "https://hotshot-delta.vercel.app/",
    sourceUrl: "https://github.com/AyushPawshe08/HotShot",
    about: [
      "HotShot is a fast, lightweight URL shortener that transforms long links into memorable short URLs. Every shortened link automatically gets a matching QR code for instant sharing.",
      "Features include custom aliases for branded links, optional expiry times to control link lifetime, and real-time click tracking from an intuitive dashboard. Links can be saved locally in the browser for quick access.",
      "Built with React and Vite for the responsive frontend, Tailwind CSS for styling, and FastAPI for high-performance backend processing. The app includes QR code generation, short code creation, and is containerized with Docker for seamless deployment.",
    ],
    stack: [
      "react",
      "vite",
      "tailwindcss",
      "axios",
      "fastapi",
      "pydantic",
      "qrcode",
      "docker",
    ],
  },
  {
    slug: "sangrahak",
    order: "08",
    status: "Local",
    title: "Sangrahak",
    description:
      "An AI-assisted inventory and depot management system with demand forecasting and stock intelligence.",
    cardIcons: ["react", "nodejs", "express", "mongodb", "redis", "python"],
    cover: {
      type: "image",
      image: "/projects/sangrahak.png",
      heading: "Sangrahak",
      subheading: "AI-assisted inventory & depot management.",
    },
    liveUrl: "https://sangrahak.example.com",
    sourceUrl: "https://github.com/AyushPawshe08/Sangrahak",
    about: [
      "Sangrahak gives depot and warehouse teams a live view of stock levels across locations, replacing manual spreadsheets with a system that flags shortages before they become stockouts.",
      "A forecasting layer looks at historical movement and seasonality to recommend reorder points and quantities, while an intelligence dashboard surfaces slow-moving and at-risk inventory.",
      "The frontend is built with React and real-time updates via Socket.io, while the backend uses Express.js with MongoDB for data persistence, Redis for caching, and Python/Flask for ML forecasting jobs.",
    ],
    stack: [
      "react",
      "vite",
      "tailwindcss",
      "express",
      "nodejs",
      "mongodb",
      "redis",
      "python",
      "flask",
      "xgboost",
      "sklearn",
      "socketio",
    ],
  },
  {
    slug: "codesageai",
    order: "09",
    status: "Live",
    title: "CodeSageAI",
    description:
      "An AI-powered code review and refactoring platform for detecting issues, improving code quality, and generating cleaner implementations.",
    cardIcons: ["react", "vite", "tailwind", "fastapi", "groq", "docker"],
    cover: {
      type: "image",
      image: "/projects/CodeSageUI.png",
      heading: "CodeSage AI",
    },
    liveUrl: "https://code-sage-ai-two.vercel.app/",
    sourceUrl: "https://github.com/AyushPawshe08/CodeSageAI",
    about: [
      "CodeSageAI uses AI to review source code for bugs, security concerns, performance bottlenecks, naming issues, error-handling gaps, documentation problems, and best-practice violations.",
      "Users can paste code into a Monaco-powered editor, select a programming language, and request either a detailed code review or an improved refactored implementation.",
      "The application combines a React and Vite frontend with a FastAPI backend, JWT authentication, SQLAlchemy persistence, Groq AI integration, and Docker-based deployment.",
    ],
    stack: [
      "react",
      "vite",
      "tailwind",
      "fastapi",
      "python",
      "groq",
      "monacoEditor",
      "sqlalchemy",
      "postgresql",
      "jwt",
      "docker",
      "nginx",
    ],
  },
];

export function getProjectBySlug(slug) {
  return projects.find((project) => project.slug === slug);
}
