import {
  SiFastapi,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiMongodb,
  SiMysql,
  SiSqlite,
  SiSqlalchemy,
  SiRedis,
  SiCelery,
  SiDocker,
  SiGit,
  SiGithubactions,
  SiTailwindcss,
  SiJsonwebtokens,
  SiLinux,
  SiNeon,
  SiQdrant,
  SiGradio,
  SiGooglegemini,
  SiPytorch,
  SiFlask,
  SiPandas,
  SiScikitlearn,
  SiHtml5,
  SiCss,
  SiHuggingface,
  SiLangchain,
  SiLanggraph,
  SiStreamlit,
  SiNumpy,
  SiPydantic,
  SiAxios,
  SiReactrouter,
  SiSocketdotio,
  SiNginx,
  SiLucide,
  SiCplusplus,
  SiGithub,
} from "react-icons/si";
import { FaAws, FaBrain, FaDatabase } from "react-icons/fa6";
import { TbBrandOpenai } from "react-icons/tb";
import { VscMcp } from "react-icons/vsc";
import { Webhook, TrendingUp, Network, Sliders, Flame, Soup, FileText, QrCode, Monitor, Combine, Server, Bot, Search, Zap, Globe } from "lucide-react";
import { PythonLogo, ViteLogo } from "@/lib/brand-logos";

// Central registry: key -> { icon, color, label, invertOnDark }.
export const TECH = {
  python: { label: "Python", icon: PythonLogo, color: "#3776AB" },
  Python: { label: "Python", icon: PythonLogo, color: "#3776AB" },
  sql: { label: "SQL", icon: FaDatabase, color: "#4479A1" },
  cpp: { label: "C++", icon: SiCplusplus, color: "#00599C" },
  fastapi: { label: "FastAPI", icon: SiFastapi, color: "#009688" },
  javascript: { label: "JavaScript", icon: SiJavascript, color: "#F7DF1E" },
  typescript: { label: "TypeScript", icon: SiTypescript, color: "#3178C6" },
  react: { label: "React", icon: SiReact, color: "#61DAFB" },
  nextjs: { label: "Next.js", icon: SiNextdotjs, color: "#000000", invertOnDark: true },
  nodejs: { label: "Node.js", icon: SiNodedotjs, color: "#5FA04E" },
  express: { label: "Express.js", icon: SiExpress, color: "#000000", invertOnDark: true },
  postgresql: { label: "PostgreSQL", icon: SiPostgresql, color: "#4169E1" },
  neon: { label: "PostgreSQL (Neon)", icon: SiNeon, color: "#00E599" },
  mongodb: { label: "MongoDB", icon: SiMongodb, color: "#47A248" },
  mysql: { label: "MySQL", icon: SiMysql, color: "#4479A1" },
  sqlite: { label: "SQLite", icon: SiSqlite, color: "#003B57" },
  sqlalchemy: { label: "SQLAlchemy", icon: SiSqlalchemy, color: "#D71F00" },
  redis: { label: "Redis", icon: SiRedis, color: "#FF4438" },
  celery: { label: "Celery", icon: SiCelery, color: "#37814A" },
  docker: { label: "Docker", icon: SiDocker, color: "#2496ED" },
  Docker: { label: "Docker", icon: SiDocker, color: "#2496ED" },
  awsEc2: { label: "AWS EC2", icon: FaAws, color: "#FF9900" },
  awsS3: { label: "AWS S3", icon: FaAws, color: "#569A31" },
  aws: { label: "AWS", icon: FaAws, color: "#FF9900" },
  awsFull: { label: "AWS (EC2, S3, RDS)", icon: FaAws, color: "#FF9900" },
  git: { label: "Git", icon: SiGit, color: "#F05032" },
  github: { label: "Git / GitHub", icon: SiGithub, color: "#181717", invertOnDark: true },
  cicd: { label: "CI/CD", icon: SiGithubactions, color: "#2088FF" },
  githubActions: { label: "GitHub Actions", icon: SiGithubactions, color: "#2088FF" },
  tailwind: { label: "Tailwind CSS", icon: SiTailwindcss, color: "#06B6D4" },
  tailwindcss: { label: "Tailwind CSS", icon: SiTailwindcss, color: "#06B6D4" },
  jwt: { label: "JWT Auth", icon: SiJsonwebtokens, color: "#000000", invertOnDark: true },
  rest: { label: "REST APIs", icon: Webhook, color: "#F97316" },
  linux: { label: "Linux", icon: SiLinux, color: "#FCC624" },
  openai: { label: "OpenAI", icon: TbBrandOpenai, color: "#412991" },
  qdrant: { label: "Qdrant", icon: SiQdrant, color: "#DC244C" },
  Qdrant: { label: "Qdrant", icon: SiQdrant, color: "#DC244C" },
  chromadb: { label: "ChromaDB", icon: FaDatabase, color: "#F97316" },
  gradio: { label: "Gradio", icon: SiGradio, color: "#FF7C00" },
  Gradio: { label: "Gradio", icon: SiGradio, color: "#FF7C00" },
  rag: { label: "Multimodal RAG", icon: FaBrain, color: "#8B5CF6" },
  RAG: { label: "Multimodal RAG", icon: FaBrain, color: "#8B5CF6" },
  ragConcept: { label: "RAG", icon: FaBrain, color: "#8B5CF6" },
  mcp: { label: "MCP", icon: VscMcp, color: "#00000" },
  MCP: { label: "MCP", icon: VscMcp, color: "#D97706" },
  fastmcp: { label: "FastMCP", icon: Zap, color: "#10B981" },
  FastMCP: { label: "FastMCP", icon: Zap, color: "#10B981" },
  httpx: { label: "HTTPX", icon: Globe, color: "#009688" },
  HTTPX: { label: "HTTPX", icon: Globe, color: "#009688" },
  trafilatura: { label: "Trafilatura", icon: FileText, color: "#EA580C" },
  Trafilatura: { label: "Trafilatura", icon: FileText, color: "#EA580C" },
  llms: { label: "LLMs", icon: Bot, color: "#F55036" },
  ragas: { label: "RAGAS", icon: Sliders, color: "#14B8A6" },
  finetuning: { label: "Fine-tuning", icon: Sliders, color: "#A855F7" },
  gemini: { label: "Google Gemini", icon: SiGooglegemini, color: "#8E75B2" },
  pytorch: { label: "PyTorch", icon: SiPytorch, color: "#EE4C2C" },
  flask: { label: "Flask", icon: SiFlask, color: "#000000", invertOnDark: true },
  pandas: { label: "Pandas", icon: SiPandas, color: "#150458", invertOnDark: true },
  "scikit-learn": { label: "Scikit-Learn", icon: SiScikitlearn, color: "#F7931E" },
  scikitlearn: { label: "Scikit-Learn", icon: SiScikitlearn, color: "#F7931E" },
  sklearn: { label: "Scikit-Learn", icon: SiScikitlearn, color: "#F7931E" },
  lightgbm: { label: "LightGBM", icon: TrendingUp, color: "#00ACC1" },
  xgboost: { label: "XGBoost", icon: Network, color: "#F05A28" },
  shap: { label: "SHAP", icon: Sliders, color: "#1B998B" },
  html: { label: "HTML5", icon: SiHtml5, color: "#E34F26" },
  css: { label: "CSS3", icon: SiCss, color: "#1572B6" },
  vite: { label: "Vite", icon: ViteLogo, color: "#646CFF" },
  transformers: { label: "Transformers", icon: SiHuggingface, color: "#FFD21E" },
  huggingface: { label: "Hugging Face", icon: SiHuggingface, color: "#FFD21E" },
  langgraph: { label: "LangGraph", icon: SiLanggraph, color: "#1C3C3C", invertOnDark: true },
  langchain: { label: "LangChain", icon: SiLangchain, color: "#1C3C3C", invertOnDark: true },
  tavily: { label: "Tavily", icon: Search, color: "#4F46E5" },
  Tavily: { label: "Tavily", icon: Search, color: "#4F46E5" },
  streamlit: { label: "Streamlit", icon: SiStreamlit, color: "#FF4B4B" },
  firecrawl: { label: "Firecrawl", icon: Flame, color: "#F97316" },
  beautifulsoup4: { label: "BeautifulSoup", icon: Soup, color: "#4B8BBE" },
  numpy: { label: "NumPy", icon: SiNumpy, color: "#013243", invertOnDark: true },
  uvicorn: { label: "Uvicorn", icon: Server, color: "#499848" },
  joblib: { label: "Joblib", icon: Combine, color: "#F59E0B" },
  groq: { label: "Groq", icon: Bot, color: "#F55036" },
  "groq-ai": { label: "Groq AI", icon: Bot, color: "#F55036" },
  reportlab: { label: "ReportLab", icon: FileText, color: "#DC2626" },
  pydantic: { label: "Pydantic", icon: SiPydantic, color: "#E92063" },
  axios: { label: "Axios", icon: SiAxios, color: "#5A29E4" },
  "react-router-dom": { label: "React Router", icon: SiReactrouter, color: "#CA4245" },
  qrcode: { label: "QR Code", icon: QrCode, color: "#000000", invertOnDark: true },
  socketio: { label: "Socket.IO", icon: SiSocketdotio, color: "#010101", invertOnDark: true },
  monacoEditor: { label: "Monaco Editor", icon: Monitor, color: "#007ACC" },
  lucideReact: { label: "Lucide", icon: SiLucide, color: "#F56565" },
  dockerCompose: { label: "Docker Compose", icon: SiDocker, color: "#2496ED" },
  nginx: { label: "Nginx", icon: SiNginx, color: "#009639" },
};

export const HOME_STACK = [
  "python",
  "javascript",
  "typescript",
  "react",
  "nextjs",
  "vite",
  "tailwind",
  "fastapi",
  "flask",
  "nodejs",
  "express",
  "mcp",
  "fastmcp",
  "langchain",
  "langgraph",
  "pytorch",
  "huggingface",
  "openai",
  "gemini",
  "groq",
  "qdrant",
  "streamlit",
  "gradio",
  "pandas",
  "numpy",
  "scikit-learn",
  "xgboost",
  "lightgbm",
  "postgresql",
  "mongodb",
  "mysql",
  "sqlite",
  "sqlalchemy",
  "redis",
  "celery",
  "docker",
  "nginx",
  "aws",
  "githubActions",
  "git",
  "linux",
  "jwt",
];

export const SKILL_CATEGORIES = [
  {
    number: "01",
    title: "Languages",
    items: ["python", "javascript", "sql", "cpp"],
  },
  {
    number: "02",
    title: "Frontend",
    items: ["react", "nextjs", "tailwind"],
  },
  {
    number: "03",
    title: "Backend",
    items: ["fastapi", "flask", "nodejs", "express", "jwt", "rest", "sqlalchemy"],
  },
  {
    number: "04",
    title: "Databases",
    items: ["postgresql", "mysql", "mongodb", "redis", "chromadb", "qdrant"],
  },
  {
    number: "05",
    title: "AI & ML",
    items: [
      "langchain",
      "langgraph",
      "ragConcept",
      "mcp",
      "fastmcp",
      "groq",
      "pytorch",
      "llms",
      "ragas",
      "finetuning",
      "huggingface",
      "numpy",
      "pandas",
    ],
  },
  {
    number: "06",
    title: "Tools & Cloud",
    items: ["docker", "awsFull", "github", "linux", "cicd", "nginx"],
  },
];

export function getTech(key) {
  if (!key) return null;
  return TECH[key] || TECH[key.toLowerCase()] || TECH[key.toUpperCase()] || null;
}
