import {
  SiPython,
  SiFastapi,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiMongodb,
  SiMysql,
  SiSqlite,
  SiSqlalchemy,
  SiRedis,
  SiCelery,
  SiDocker,
  SiGit,
  SiGithubactions,
  SiTailwindcss,
  SiJsonwebtokens,
  SiLinux,
  SiNeon,
  SiQdrant,
  SiGradio,
  SiGooglegemini,
  SiPytorch,
} from "react-icons/si";
import { FaAws, FaBrain } from "react-icons/fa6";
import { TbBrandOpenai } from "react-icons/tb";
import { Webhook } from "lucide-react";

// Central registry: key -> { icon, color, label }.
// Reused by the home Stack section, project cards, and project detail pages
// so every tech badge looks the same everywhere.
export const TECH = {
  python: { label: "Python", icon: SiPython, color: "#3776AB" },
  fastapi: { label: "FastAPI", icon: SiFastapi, color: "#009688" },
  javascript: { label: "JavaScript", icon: SiJavascript, color: "#F7DF1E" },
  typescript: { label: "TypeScript", icon: SiTypescript, color: "#3178C6" },
  react: { label: "React", icon: SiReact, color: "#61DAFB" },
  nextjs: { label: "Next.js", icon: SiNextdotjs, color: "#000000" },
  nodejs: { label: "Node.js", icon: SiNodedotjs, color: "#339933" },
  express: { label: "Express.js", icon: SiExpress, color: "#000000" },
  postgresql: { label: "PostgreSQL", icon: SiPostgresql, color: "#4169E1" },
  neon: { label: "PostgreSQL (Neon)", icon: SiNeon, color: "#00E599" },
  mongodb: { label: "MongoDB", icon: SiMongodb, color: "#47A248" },
  mysql: { label: "MySQL", icon: SiMysql, color: "#4479A1" },
  sqlite: { label: "SQLite", icon: SiSqlite, color: "#003B57" },
  sqlalchemy: { label: "SQLAlchemy", icon: SiSqlalchemy, color: "#D71F00" },
  redis: { label: "Redis", icon: SiRedis, color: "#DC382D" },
  celery: { label: "Celery", icon: SiCelery, color: "#37814A" },
  docker: { label: "Docker", icon: SiDocker, color: "#2496ED" },
  awsEc2: { label: "AWS EC2", icon: FaAws, color: "#FF9900" },
  awsS3: { label: "AWS S3", icon: FaAws, color: "#569A31" },
  aws: { label: "AWS", icon: FaAws, color: "#FF9900" },
  git: { label: "Git", icon: SiGit, color: "#F05032" },
  githubActions: { label: "GitHub Actions", icon: SiGithubactions, color: "#2088FF" },
  tailwind: { label: "Tailwind CSS", icon: SiTailwindcss, color: "#06B6D4" },
  jwt: { label: "JWT Auth", icon: SiJsonwebtokens, color: "#000000" },
  rest: { label: "REST APIs", icon: Webhook, color: "#F97316" },
  linux: { label: "Linux", icon: SiLinux, color: "#FCC624" },
  openai: { label: "OpenAI LLM", icon: TbBrandOpenai, color: "#412991" },
  qdrant: { label: "Qdrant", icon: SiQdrant, color: "#DC2626" },
  Qdrant: { label: "Qdrant", icon: SiQdrant, color: "#DC2626" },
  gradio: { label: "Gradio", icon: SiGradio, color: "#FF7C00" },
  Gradio: { label: "Gradio", icon: SiGradio, color: "#FF7C00" },
  rag: { label: "Multimodal RAG", icon: FaBrain, color: "#8B5CF6" },
  RAG: { label: "Multimodal RAG", icon: FaBrain, color: "#8B5CF6" },
  Docker: { label: "Docker", icon: SiDocker, color: "#2496ED" },
  gemini: { label: "Google Gemini", icon: SiGooglegemini, color: "#4E75F6" },
  pytorch: { label: "PyTorch", icon: SiPytorch, color: "#EE4C2C" },
};
